[profile.default]
src = 'src'
out = 'artifacts'
lib = 'lib'
test = 'src'
no_match_test = "FFI|LongRunning"
optimizer = true
optimizer_runs = 1000000
bytecode_hash = "none"

solc = "0.8.17"

allow_paths = ["../../node_modules"]
